language: java

jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - source ./scripts/ci/dependencies.sh

install: mvn install

after_success:
  - mvn cobertura:cobertura coveralls:cobertura 

branches:
  except:
    - gh-pages

notifications:
  email:
    - charliel@lab41.org
    - erickt@lab41.org
    - karthikr@lab41.org
    - kylef@lab41.org
